<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE facturas [
    <!ELEMENT facturas (factura+)>
    <!ELEMENT factura (datos_emisor, datos_cliente, detalles_factura, importe)>
    <!ELEMENT datos_emisor (nombre, cif, telefono)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT cif (#PCDATA)>
    <!ELEMENT telefono (#PCDATA)>
    <!ELEMENT datos_cliente (nombre, cif, telefono)>
    <!ELEMENT detalles_factura (articulo+)>
    <!ELEMENT articulo (descripcion, cantidad, oferta?, pvp)>
    <!ELEMENT descripcion (#PCDATA)>
    <!ELEMENT cantidad (#PCDATA)>
    <!ELEMENT oferta EMPTY>
    <!ELEMENT pvp (#PCDATA)>
    <!ELEMENT importe (#PCDATA)>

    <!ATTLIST factura numero CDATA ID #REQUIRED>
    <!ATTLIST factura fecha CDATA #REQUIRED>
    <!ATTLIST detalles_factura importe CDATA ID #REQUIRED>
    <!ATTLIST articulo codigo ID #REQUIRED>
    <!ATTLIST articulo tipo (Libro | DVD | Varios) #IMPLIED>
]>

<facturas>
    <factura numero="27" fecha="18/12/2013">
        <datos_emisor>
            <nombre>Librería Pérez</nombre>
            <cif>44555666B</cif>
            <telefono>777888999</telefono>
        </datos_emisor>
        <datos_cliente>
            <nombre>Biblioteca Txantrea</nombre>
            <cif>33111222A</cif>
            <telefono>333999444</telefono>
        </datos_cliente>
        <detalles_factura importe="85€">
            <articulo codigo="AW7" tipo="Libro">
                <descripcion>Analítica Web 2.0</descripcion>
                <cantidad>1</cantidad>
                <oferta/>
                <pvp>25€</pvp>
            </articulo>
            <articulo codigo="CP5" tipo="DVD">
                <descripcion>Curso de HTML</descripcion>
                <cantidad>2</cantidad>
                <pvp>30€</pvp>
            </articulo>
        </detalles_factura>
    </factura>
</facturas>