=== alejandroelv/XML/Relación ejercicios XML/ejercicio3.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="html">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="section" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="headline">
                            <xs:complexType mixed="true">
                                <xs:attribute name="size" use="required">
                                    <xs:simpleType>
                                        <xs:restriction base="xs:integer">
                                            <xs:minInclusive value="1"/>
                                            <xs:maxInclusive value="6"/>
                                        </xs:restriction>
                                    </xs:simpleType>
                                </xs:attribute>
                            </xs:complexType>
                        </xs:element>
                        <xs:element name="ul">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="li" minOccurs="2" maxOccurs="3">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:string">
                                                <xs:maxLength value="100"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== alejandroelv/XML/Relación ejercicios XML/ejercicio3.xml
<?xml version="1.0" encoding="UTF-8"?>

<html xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio3.xsd">
    <section>
        <headline size="2">Ejemplo de XML</headline>
        <ul>
            <li> datos estructurados </li>
            <li> intercambio de datos </li>
        </ul>
    </section>
    <section>
        <headline size="3">Otro ejemplo</headline>
        <ul>
            <li> datos opcionales </li>
            <li> esquemas opcionales </li>
            <li> un solo elemento ra√≠z </li>
        </ul>
    </section>
</html>
