<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE alumno [
    <!ELEMENT alumno (nombre, apellidos, repite?, plan)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT apellidos (#PCDATA)>
    <!ELEMENT repite EMPTY>
    <!ELEMENT plan (asignaturas)>
    <!ELEMENT asignaturas (asignatura+)>
    <!ELEMENT asignatura (nombre, abreviatura, matricula?)>
    <!ELEMENT abreviatura (#PCDATA)>
    <!ELEMENT matricula (fecha, tipo)>
    <!ELEMENT fecha (#PCDATA)>
    <!ELEMENT tipo (#PCDATA)>
    
    <!ATTLIST alumno numero ID NMTOKENS #REQUIRED>
    <!ATTLIST asignaturas curso (1|2) #REQUIRED>
    <!ATTLIST asignatura cod ID NMTOKENS #REQUIRED>
]>
<alumno numero="323">
    <nombre>Juan</nombre>
    <apellidos>Rodríguez Marín</apellidos>
    <repite/>
    <plan>
        <asignaturas curso="1">
            <asignatura cod="123">
                <nombre>Lenguajes de Marcas y Sistemas de Información</nombre>
                <abreviatura>LMSI</abreviatura>
                <matricula>
                    <fecha>23/10/2015</fecha>
                    <tipo>Ordinaria</tipo>
                </matricula>
            </asignatura>
            <asignatura cod="124">
                <nombre>Sistemas de Gestión Empresarial</nombre>
                <abreviatura>SGE</abreviatura>
            </asignatura>
        </asignaturas>
    </plan>
</alumno>