=== alejandroelv/XML/Relación ejercicios XML/ejercicio4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

<xsd:complexType name="tipoPedido">
    <xsd:sequence>
        <xsd:element name="direccionEnvio" type="tipoDireccion"/>
        <xsd:element name="direccionFiscal" type="tipoDireccion"/>
        <xsd:element minOccurs="0" ref="comentario"/>
        <xsd:element name="articulos" type="Articulos"/>
    </xsd:sequence>
    <xsd:attribute name="fechaPedido" type="xsd:date"/>
</xsd:complexType>

<xsd:complexType name="tipoDireccion">
    <xsd:sequence>
        <xsd:element name="nombre" type="xsd:string"/>
        <xsd:element name="calle" type="xsd:string"/>
        <xsd:element name="localidad" type="xsd:string"/>
        <xsd:element name="provincia" type="xsd:string"/>
        <xsd:element name="cp" type="xsd:string"/>
    </xsd:sequence>
    <xsd:attribute fixed="ES" name="pais" type="xsd:NMTOKEN"/>
</xsd:complexType>

<xsd:complexType name="Articulos">
    <xsd:sequence>
        <xsd:element maxOccurs="unbounded" minOccurs="0" name="articulo">
            <xsd:complexType>
                <xsd:sequence>
                    <xsd:element name="nombreProducto" type="xsd:string"/>
                    <xsd:element name="cantidad">
                        <xsd:simpleType>
                            <xsd:restriction base="xsd:positiveInteger">
                                <xsd:maxExclusive value="100"/>
                            </xsd:restriction>
                        </xsd:simpleType>
                    </xsd:element>
                    <xsd:element name="precio" type="xsd:decimal"/>
                    <xsd:element minOccurs="0" ref="comentario"/>
                    <xsd:element minOccurs="0" name="fechaEnvio" type="xsd:date"/>
                </xsd:sequence>
                <xsd:attribute name="codigo" type="codigoProducto" use="required"/>
            </xsd:complexType>
        </xsd:element>
    </xsd:sequence>
</xsd:complexType>

<xsd:simpleType name="codigoProducto">
    <xsd:restriction base="xsd:string">
        <xsd:pattern value="\d{3}-[A-Z]{2}"/>
    </xsd:restriction>
</xsd:simpleType>

<xsd:element name="pedido" type="tipoPedido"/>
<xsd:element name="comentario" type="xsd:string"/>
</xsd:schema>

=== alejandroelv/XML/Relación ejercicios XML/ejercicio4.xml
<pedido fechaPedido="2021-11-29" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejercicio4.xsd">
    <direccionEnvio>
        <nombre>Alejandro Elvira Cervera</nombre>
        <calle>Calle Falsa 123</calle>
        <localidad>Granada</localidad>
        <provincia>Granada</provincia>
        <cp>18010</cp>
    </direccionEnvio>
    <direccionFiscal>
        <nombre>Alejandro Elvira Cervera</nombre>
        <calle>Calle Falsa 123</calle>
        <localidad>Granada</localidad>
        <provincia>Granada</provincia>
        <cp>18010</cp>
    </direccionFiscal>
    <articulos>
        <articulo codigo="123-AB">
            <nombreProducto>Rat√≥n Gaming Sharkoon Drakonia</nombreProducto>
            <cantidad>1</cantidad>
            <precio>32.98</precio>
            <fechaEnvio>2021-12-02</fechaEnvio>
        </articulo>
        <articulo codigo="789-YZ">
            <nombreProducto>Corsair Vengeance LPX DDR4 3200MHz PC4-25600 8GB CL16</nombreProducto>
            <cantidad>2</cantidad>
            <precio>74.34</precio>
            <fechaEnvio>2021-12-02</fechaEnvio>
        </articulo>
    </articulos>
</pedido>
